import { Board, BoardItem } from '../types';
import { colors } from '../theme';

export function createSeedItems(): BoardItem[] {
  return [
    {
      id: 'hero-title',
      type: 'text',
      x: 60,
      y: 80,
      width: 960,
      height: 160,
      zIndex: 1,
      backgroundColor: colors.paper,
      color: colors.ink,
      text: 'A place for unfinished ideas.\n\nCollect the pieces. Move them until they make sense.',
      fontSize: 42,
      role: 'title',
      fontWeight: '500',
      markdown: true,
    },
    {
      id: 'pottery-image',
      type: 'image',
      x: 60,
      y: 280,
      width: 450,
      height: 338,
      zIndex: 1,
      backgroundColor: colors.paper,
      uri: '',
      assetKey: 'pottery',
      alt: 'Hands shaping clay on a pottery wheel',
    },
    {
      id: 'human-note',
      type: 'text',
      x: 540,
      y: 280,
      width: 380,
      height: 205,
      zIndex: 1,
      backgroundColor: colors.clay,
      color: colors.ink,
      text: '## Keep it human\n\nKeep it **useful**.',
      fontSize: 28,
      role: 'note',
      fontWeight: '400',
      markdown: true,
    },
    {
      id: 'wildflower-image',
      type: 'image',
      x: 1130,
      y: 155,
      width: 330,
      height: 413,
      zIndex: 1,
      backgroundColor: colors.paper,
      uri: '',
      assetKey: 'wildflower',
      alt: 'Amber wildflowers in a cream vase by a sunlit wall',
    },
    {
      id: 'palette-note',
      type: 'text',
      x: 720,
      y: 615,
      width: 340,
      height: 160,
      zIndex: 1,
      backgroundColor: colors.paper,
      color: colors.ink,
      text: '### Palette\n\n- warm\n- useful\n- unforced\n\nWrite `markdown` on any note.',
      fontSize: 20,
      role: 'body',
      fontWeight: '400',
      markdown: true,
    },
    {
      id: 'flow-region',
      type: 'region',
      x: 60,
      y: 700,
      width: 720,
      height: 320,
      zIndex: 0,
      label: 'Water flow',
      frameColor: 'rgba(233,178,127,0.22)',
    },
    {
      id: 'task-root',
      type: 'task',
      x: 100,
      y: 760,
      width: 260,
      height: 110,
      zIndex: 2,
      backgroundColor: colors.paperStrong,
      text: 'Gather clay',
      done: false,
      dependsOn: [],
      parentId: 'flow-region',
    },
    {
      id: 'task-child',
      type: 'task',
      x: 420,
      y: 760,
      width: 280,
      height: 110,
      zIndex: 2,
      backgroundColor: colors.paperStrong,
      text: 'Shape the vessel',
      done: false,
      dependsOn: ['task-root'],
      parentId: 'flow-region',
    },
    {
      id: 'flow-edge',
      type: 'connector',
      x: 0,
      y: 0,
      width: 1,
      height: 1,
      zIndex: 3,
      fromId: 'task-root',
      toId: 'task-child',
      fromSide: 'right',
      toSide: 'left',
      thickness: 2,
      glowing: false,
      color: colors.ink,
    },
    {
      id: 'mind-root',
      type: 'mindmap',
      x: 1000,
      y: 700,
      width: 240,
      height: 160,
      zIndex: 2,
      backgroundColor: colors.paper,
      text: 'Field notes',
      children: ['mind-child-a', 'mind-child-b'],
      collapsed: false,
      branchColor: colors.clay,
    },
    {
      id: 'mind-child-a',
      type: 'mindmap',
      x: 900,
      y: 900,
      width: 180,
      height: 100,
      zIndex: 2,
      backgroundColor: colors.paper,
      text: 'Observe',
      children: [],
      branchColor: colors.clay,
    },
    {
      id: 'mind-child-b',
      type: 'mindmap',
      x: 1140,
      y: 900,
      width: 180,
      height: 100,
      zIndex: 2,
      backgroundColor: colors.paper,
      text: 'Arrange',
      children: [],
      branchColor: colors.clay,
    },
  ];
}

export function createMainBoard(): Board {
  return {
    id: 'main',
    name: 'Main board',
    items: createSeedItems(),
    updatedAt: Date.now(),
  };
}

export function uid(prefix = 'item'): string {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}
